"""
临时测试脚本：验证 ThemeManager 样式表生成（独立版本）
不依赖 PySide6，直接模拟样式表生成逻辑
"""
from pathlib import Path

# 模拟 DarkThemeColors（从 design_system.py 提取）
class DarkThemeColors:
    BG_APP = "#0A0E14"
    BG_SURFACE = "#141922"
    BG_ELEVATED = "#1C2128"
    BG_HOVER = "#252D38"
    BG_ACTIVE = "#2D3642"
    BG_INPUT = "#1A1F29"

    TEXT_PRIMARY = "#E6EDF3"
    TEXT_SECONDARY = "#9DA9BB"
    TEXT_TERTIARY = "#6B7785"
    TEXT_DISABLED = "#484F5C"

    BRAND_PRIMARY = "#0EA5E9"
    BRAND_HOVER = "#0284C7"
    BRAND_ACTIVE = "#0369A1"
    BRAND_SUBTLE = "#082F49"

    SUCCESS = "#10B981"
    SUCCESS_BG = "#064E3B"
    SUCCESS_BORDER = "#065F46"

    WARNING = "#F59E0B"
    WARNING_BG = "#78350F"
    WARNING_BORDER = "#92400E"

    ERROR = "#EF4444"
    ERROR_BG = "#7F1D1D"
    ERROR_BORDER = "#991B1B"

    INFO = "#3B82F6"
    INFO_BG = "#1E3A8A"
    INFO_BORDER = "#1E40AF"

    BORDER_DEFAULT = "#30363D"
    BORDER_SUBTLE = "#21262D"
    BORDER_EMPHASIS = "#525964"

# 模拟字体和尺寸常量
class FONT_FAMILY:
    @staticmethod
    def get_sans_serif_family():
        return '"Microsoft YaHei UI", "Microsoft YaHei", "Segoe UI", sans-serif'

    @staticmethod
    def get_monospace_family():
        return 'Consolas, Monaco, monospace'

class FONT_SIZE:
    H1 = 28
    H2 = 22
    H3 = 18
    H4 = 16
    BODY_L = 15
    BODY = 14
    BODY_S = 13
    CAPTION = 12

class LINE_HEIGHT:
    TIGHT = 1.2
    NORMAL = 1.5
    RELAXED = 1.7

class FONT_WEIGHT:
    REGULAR = 400
    MEDIUM = 500
    SEMIBOLD = 600
    BOLD = 700

class RADIUS:
    SM = 4
    MD = 6
    LG = 8
    XL = 12
    XXL = 16
    FULL = 9999

class PADDING:
    CARD_PADDING = 24

class BORDER_SHADOW:
    # (border_color, bottom_border_color, bottom_width)
    DARK_LIGHT = ("#21262D", "#1A1F29", 2)
    DARK_MEDIUM = ("#30363D", "#21262D", 3)
    LIGHT_LIGHT = ("#E2E8F0", "#CBD5E1", 2)
    LIGHT_MEDIUM = ("#CBD5E1", "#94A3B8", 3)

def generate_stylesheet(colors, mode="dark"):
    """
    从 theme_manager.py 复制的样式表生成逻辑
    """
    font_family = FONT_FAMILY.get_sans_serif_family()
    mono_family = FONT_FAMILY.get_monospace_family()

    is_dark = mode == "dark"
    shadow_light = BORDER_SHADOW.DARK_LIGHT if is_dark else BORDER_SHADOW.LIGHT_LIGHT
    shadow_medium = BORDER_SHADOW.DARK_MEDIUM if is_dark else BORDER_SHADOW.LIGHT_MEDIUM

    stylesheet = f"""
/* ============================================================================
   AutoLabeler Theme: {mode.capitalize()}
   Generated by ThemeManager
   ============================================================================ */

/* Global Base Styles */
* {{
    font-family: {font_family};
    /* Transitions handled by QPropertyAnimation in Python */
}}

QWidget {{
    background-color: {colors.BG_APP};
    color: {colors.TEXT_PRIMARY};
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.REGULAR};
}}

/* ============================================================================
   Application Shell
   ============================================================================ */

#workbenchView {{
    background-color: {colors.BG_APP};
}}

#loginView {{
    background-color: {colors.BG_APP};
}}

/* ============================================================================
   Side Navigation
   ============================================================================ */

#sideNav {{
    background-color: {colors.BG_APP};
    border-right: 1px solid {colors.BORDER_SUBTLE};
    min-width: 240px;
    max-width: 240px;
}}

#navMark {{
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                                stop:0 {colors.BRAND_PRIMARY},
                                stop:1 {colors.BRAND_HOVER});
    color: #FFFFFF;
    font-size: 18px;
    font-weight: {FONT_WEIGHT.BOLD};
    border-radius: {RADIUS.LG}px;
    min-width: 40px;
    max-width: 40px;
    min-height: 40px;
    max-height: 40px;
}}

#navBrand {{
    color: {colors.TEXT_PRIMARY};
    font-size: 16px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    line-height: {LINE_HEIGHT.TIGHT};
}}

#navSection {{
    color: {colors.TEXT_TERTIARY};
    font-size: 11px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    letter-spacing: 0.5px;
    padding: 20px 20px 8px;
}}

QPushButton[objectName="navButton"] {{
    background-color: transparent;
    color: {colors.TEXT_SECONDARY};
    border: none;
    border-left: 3px solid transparent;
    border-radius: {RADIUS.MD}px;
    padding: 10px 20px 10px 17px;
    margin: 2px 12px;
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.MEDIUM};
    text-align: left;
}}

QPushButton[objectName="navButton"]:hover {{
    background-color: {colors.BG_SURFACE};
    color: {colors.TEXT_PRIMARY};
}}

QPushButton[objectName="navButton"][selected="true"] {{
    background-color: {colors.BRAND_SUBTLE};
    color: {colors.BRAND_PRIMARY};
    border-left: 3px solid {colors.BRAND_PRIMARY};
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

/* ============================================================================
   Buttons
   ============================================================================ */

#primaryButton {{
    background-color: {colors.BRAND_PRIMARY};
    color: #FFFFFF;
    border: none;
    border-radius: {RADIUS.MD}px;
    padding: 14px 28px;
    font-size: 15px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

#primaryButton:hover {{
    background-color: {colors.BRAND_HOVER};
}}

#primaryButton:pressed {{
    background-color: {colors.BRAND_ACTIVE};
}}

#primaryButton:disabled {{
    background-color: {colors.BORDER_DEFAULT};
    color: {colors.TEXT_TERTIARY};
}}

#secondaryButton {{
    background-color: transparent;
    color: {colors.TEXT_SECONDARY};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
    padding: 12px 24px;
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.MEDIUM};
}}

#secondaryButton:hover {{
    background-color: {colors.BG_HOVER};
    border-color: {colors.BORDER_EMPHASIS};
    color: {colors.TEXT_PRIMARY};
}}

#secondaryButton:pressed {{
    background-color: {colors.BG_ACTIVE};
}}

#secondaryButton:disabled {{
    background-color: transparent;
    color: {colors.TEXT_TERTIARY};
    border-color: {colors.BORDER_DEFAULT};
    cursor: not-allowed;
}}

/* ============================================================================
   Input Fields
   ============================================================================ */

#formInput, QLineEdit {{
    background-color: {colors.BG_INPUT};
    color: {colors.TEXT_PRIMARY};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
    padding: 12px 14px;
    font-size: {FONT_SIZE.BODY}px;
}}

#formInput:focus, QLineEdit:focus {{
    border-color: {colors.BRAND_PRIMARY};
    outline: 2px solid rgba(14, 165, 233, 0.2);
    outline-offset: 0px;
}}

#formInput:disabled, QLineEdit:disabled {{
    background-color: {colors.BG_APP};
    color: {colors.TEXT_TERTIARY};
}}

QComboBox {{
    background-color: {colors.BG_INPUT};
    color: {colors.TEXT_PRIMARY};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
    padding: 10px 12px;
    font-size: {FONT_SIZE.BODY}px;
}}

QComboBox:hover {{
    border-color: {colors.BRAND_PRIMARY};
}}

QComboBox::drop-down {{
    border: none;
}}

QComboBox QAbstractItemView {{
    background-color: {colors.BG_ELEVATED};
    border: 1px solid {colors.BORDER_DEFAULT};
    selection-background-color: {colors.BRAND_SUBTLE};
    selection-color: {colors.BRAND_PRIMARY};
}}

/* ============================================================================
   Cards and Panels
   ============================================================================ */

QFrame[objectName*="Card"], QFrame[objectName*="Panel"] {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_SUBTLE};
    border-bottom: 2px solid {shadow_light[1]};
    border-radius: {RADIUS.LG}px;
    padding: {PADDING.CARD_PADDING}px;
}}

#homeHero, #homeModulePanel, #homeSupportPanel {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_SUBTLE};
    border-bottom: 2px solid {shadow_light[1]};
    border-radius: {RADIUS.LG}px;
}}

#aiPreview {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_SUBTLE};
    border-radius: {RADIUS.LG}px;
}}

/* ============================================================================
   Typography
   ============================================================================ */

#toolTitle {{
    font-size: {FONT_SIZE.H1}px;
    font-weight: {FONT_WEIGHT.BOLD};
    color: {colors.TEXT_PRIMARY};
    line-height: {LINE_HEIGHT.TIGHT};
}}

#loginCard {{
    background-color: {colors.BG_ELEVATED};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.XL}px;
}}

#loginCardContainer {{
    background: {colors.BG_SURFACE};
}}

/* ============================================================================
   End of Stylesheet
   ============================================================================ */
    """

    return stylesheet.strip()


def test_stylesheet_generation():
    """测试样式表生成并保存到文件"""
    print("=" * 80)
    print("主题样式表生成测试（独立版本）")
    print("=" * 80)

    project_root = Path(__file__).parent
    colors = DarkThemeColors()

    # 生成暗色主题样式表
    print("\n[1] 生成暗色主题样式表...")
    dark_stylesheet = generate_stylesheet(colors, mode="dark")

    # 保存到文件
    output_file = project_root / "_generated_stylesheet_dark.qss"
    output_file.write_text(dark_stylesheet, encoding="utf-8")
    print(f"    [OK] 已保存到: {output_file}")
    print(f"    [OK] 样式表长度: {len(dark_stylesheet)} 字符")

    # 检查是否存在未替换的模板变量
    print("\n[2] 检查模板变量替换...")
    unresolved = []
    for line_num, line in enumerate(dark_stylesheet.split('\n'), 1):
        if '{' in line and 'qlineargradient' not in line:
            # 检查是否有看起来像模板变量的内容
            if 'colors.' in line or '{FONT_' in line or '{LINE_HEIGHT' in line or '{RADIUS' in line:
                unresolved.append((line_num, line.strip()))

    if unresolved:
        print(f"    [ERROR] 发现 {len(unresolved)} 处未替换的模板变量:")
        for line_num, line in unresolved[:10]:
            print(f"      第 {line_num} 行: {line}")
    else:
        print("    [OK] 未发现未替换的模板变量")

    # 显示样式表的前几行
    print("\n[3] 样式表预览（前30行）:")
    print("-" * 80)
    lines = dark_stylesheet.split('\n')
    for i in range(min(30, len(lines))):
        print(f"{i+1:3d} | {lines[i]}")
    print("-" * 80)

    # 检查关键样式规则
    print("\n[4] 检查关键样式规则...")
    rules_to_check = [
        ("QWidget {", "全局QWidget样式块"),
        ("background-color: #0A0E14", "BG_APP颜色值"),
        ("color: #E6EDF3", "TEXT_PRIMARY颜色值"),
        ("#loginCard {", "登录卡片样式块"),
        ("#workbenchView {", "工作台视图样式块"),
    ]

    for rule, desc in rules_to_check:
        if rule in dark_stylesheet:
            print(f"    [OK] 找到 {desc}")
        else:
            print(f"    [ERROR] 未找到 {desc}")

    # 检查QSS语法问题
    print("\n[5] 检查潜在的QSS语法问题...")
    issues = []

    # 检查花括号匹配
    open_braces = dark_stylesheet.count('{')
    close_braces = dark_stylesheet.count('}')
    if open_braces != close_braces:
        issues.append(f"花括号不匹配: {open_braces} 个 '{{' vs {close_braces} 个 '}}'")
    else:
        print(f"    [OK] 花括号匹配 ({open_braces} 对)")

    # 检查是否有 line-height 属性（QSS不支持）
    if 'line-height:' in dark_stylesheet:
        line_height_count = dark_stylesheet.count('line-height:')
        issues.append(f"发现 {line_height_count} 处 'line-height' 属性（QSS不支持此CSS属性）")

        # 找出所有包含 line-height 的行
        print(f"    [ERROR] 发现 {line_height_count} 处不支持的 'line-height' 属性:")
        for line_num, line in enumerate(dark_stylesheet.split('\n'), 1):
            if 'line-height:' in line:
                print(f"      第 {line_num} 行: {line.strip()}")

    # 检查是否有其他不支持的CSS属性
    unsupported_properties = ['transition:', 'transform:', 'box-shadow:', 'cursor:']
    for prop in unsupported_properties:
        if prop in dark_stylesheet:
            count = dark_stylesheet.count(prop)
            issues.append(f"发现 {count} 处可能不支持的属性: {prop}")

    if not issues:
        print("    [OK] 未发现明显的语法问题")
    else:
        print("    发现以下问题:")
        for issue in issues:
            print(f"      - {issue}")

    print("\n" + "=" * 80)
    print("测试完成")
    print("=" * 80)

    return dark_stylesheet, issues


if __name__ == "__main__":
    stylesheet, issues = test_stylesheet_generation()
