"""
Theme Manager for AutoLabeler
==============================

Generates the application's stable light-theme stylesheet.

Version: 1.0
Last Updated: 2026-08-24
"""

from __future__ import annotations

from gui.design_system import (
    LIGHT_THEME,
    FONT_FAMILY,
    FONT_SIZE,
    FONT_WEIGHT,
    LINE_HEIGHT,
    RADIUS,
    BORDER_SHADOW,
)


class ThemeManager:
    """
    Singleton theme manager for the AutoLabeler application.

    Responsibility:
    - Generate the complete light QSS stylesheet
    """

    _instance: ThemeManager | None = None

    def __new__(cls) -> ThemeManager:
        """Singleton pattern: ensure only one instance exists."""
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self) -> None:
        """Initialize theme manager (only once due to singleton pattern)."""
        if self._initialized:
            return

        self._light_stylesheet = self._generate_stylesheet()
        self._initialized = True

    def get_stylesheet(self) -> str:
        """Return the complete light-theme QSS stylesheet."""
        return self._light_stylesheet

    def _generate_stylesheet(self) -> str:
        """
        Generate the complete light-theme QSS stylesheet.

        Returns:
            Complete QSS stylesheet string
        """
        # Font family setup
        font_family = FONT_FAMILY.get_sans_serif_family()
        mono_family = FONT_FAMILY.get_monospace_family()

        colors = LIGHT_THEME

        # Border shadow helpers
        shadow_light = BORDER_SHADOW.LIGHT_LIGHT
        shadow_medium = BORDER_SHADOW.LIGHT_MEDIUM

        # Note: QSS does not support CSS transition property.
        # Theme transitions are not needed for the stable light theme.
        # Component animations use QPropertyAnimation in gui/animations.py.

        stylesheet = f"""
/* ============================================================================
   AutoLabeler Theme: Light
   Generated by ThemeManager
   ============================================================================ */

/* Global Base Styles */
* {{
    font-family: {font_family};
    /* Transitions handled by QPropertyAnimation in Python */
}}

QWidget {{
    background-color: {colors.BG_APP};
    color: {colors.TEXT_PRIMARY};
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.REGULAR};
}}

/* ============================================================================
   Application Shell
   ============================================================================ */

#workbenchView {{
    background-color: {colors.BG_APP};
}}

#loginView {{
    background-color: {colors.BG_APP};
}}

/* ============================================================================
   Side Navigation
   ============================================================================ */

#sideNav {{
    background-color: {colors.BG_APP};
    border-right: 1px solid {colors.BORDER_SUBTLE};
    min-width: 240px;
    max-width: 240px;
}}

#navMark {{
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                                stop:0 {colors.BRAND_PRIMARY},
                                stop:1 {colors.BRAND_HOVER});
    color: #FFFFFF;
    font-size: 18px;
    font-weight: {FONT_WEIGHT.BOLD};
    border-radius: {RADIUS.LG}px;
    min-width: 40px;
    max-width: 40px;
    min-height: 40px;
    max-height: 40px;
}}

#navBrand {{
    color: {colors.TEXT_PRIMARY};
    font-size: 16px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    line-height: {LINE_HEIGHT.TIGHT};
}}

#navSection {{
    color: {colors.TEXT_TERTIARY};
    font-size: 11px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    letter-spacing: 0.5px;
    padding: 20px 20px 8px;
}}

QPushButton#navButton,
QPushButton#navFlowButton,
QPushButton#navUtilityButton {{
    background-color: transparent;
    color: {colors.TEXT_SECONDARY};
    border: none;
    border-left: 3px solid transparent;
    border-radius: {RADIUS.MD}px;
    padding: 10px 20px 10px 17px;
    margin: 2px 12px;
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.MEDIUM};
    text-align: left;
}}

QPushButton#navButton:hover,
QPushButton#navFlowButton:hover,
QPushButton#navUtilityButton:hover {{
    background-color: {colors.BG_SURFACE};
    color: {colors.TEXT_PRIMARY};
}}

QPushButton#navButton[selected="true"],
QPushButton#navFlowButton[selected="true"],
QPushButton#navUtilityButton[selected="true"] {{
    background-color: {colors.BRAND_SUBTLE};
    color: {colors.BRAND_PRIMARY};
    border-left: 3px solid {colors.BRAND_PRIMARY};
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

#navStepNumber, #navUtilityBadge {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.SM}px;
    color: {colors.TEXT_SECONDARY};
}}

#navStepTitle {{
    color: {colors.TEXT_PRIMARY};
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

#navStepSubtitle {{
    color: {colors.TEXT_TERTIARY};
    font-size: {FONT_SIZE.CAPTION}px;
}}

QPushButton#navFlowButton[selected="true"] #navStepNumber,
QPushButton#navFlowButton[selected="true"] #navUtilityBadge {{
    background-color: {colors.BRAND_PRIMARY};
    border-color: {colors.BRAND_PRIMARY};
    color: #FFFFFF;
}}

QPushButton#navFlowButton[selected="true"] #navStepTitle,
QPushButton#navFlowButton[selected="true"] #navStepSubtitle,
QPushButton#navUtilityButton[selected="true"] #navStepTitle,
QPushButton#navUtilityButton[selected="true"] #navStepSubtitle {{
    color: {colors.TEXT_PRIMARY};
}}

/* ============================================================================
   Buttons
   ============================================================================ */

#primaryButton {{
    background-color: {colors.BRAND_PRIMARY};
    color: #FFFFFF;
    border: none;
    border-radius: {RADIUS.MD}px;
    padding: 14px 28px;
    font-size: 15px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

#primaryButton:hover {{
    background-color: {colors.BRAND_HOVER};
}}

#primaryButton:pressed {{
    background-color: {colors.BRAND_ACTIVE};
}}

#primaryButton:disabled {{
    background-color: {colors.BORDER_DEFAULT};
    color: {colors.TEXT_TERTIARY};
}}

#secondaryButton {{
    background-color: transparent;
    color: {colors.TEXT_SECONDARY};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
    padding: 12px 24px;
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.MEDIUM};
}}

#secondaryButton:hover {{
    background-color: {colors.BG_HOVER};
    border-color: {colors.BORDER_EMPHASIS};
    color: {colors.TEXT_PRIMARY};
}}

#secondaryButton:pressed {{
    background-color: {colors.BG_ACTIVE};
}}

#secondaryButton:disabled {{
    background-color: transparent;
    color: {colors.TEXT_TERTIARY};
    border-color: {colors.BORDER_DEFAULT};
}}

/* Keep the dense desktop tool chrome usable in small windows. */
QPushButton#primaryButton {{
    min-height: 36px;
    padding: 8px 16px;
}}

QPushButton#secondaryButton,
QPushButton#supportActionButton,
QPushButton#manualNavButton,
QPushButton#manualStepButton,
QPushButton#tabButton,
QPushButton#tabButtonActive,
QPushButton#advancedToggleButton,
QPushButton#taskBackButton,
QPushButton#taskDeleteButton {{
    min-height: 34px;
    padding: 7px 13px;
}}

QPushButton#tabButton,
QPushButton#tabButtonActive,
QPushButton#advancedToggleButton {{
    background-color: {colors.BG_SURFACE};
    text-align: left;
}}

QPushButton#tabButton:hover,
QPushButton#tabButtonActive:hover,
QPushButton#advancedToggleButton:hover {{
    background-color: {colors.BG_HOVER};
    border-color: {colors.BORDER_EMPHASIS};
}}

QPushButton#tabButton:checked,
QPushButton#tabButtonActive,
QPushButton#advancedToggleButton:checked {{
    background-color: {colors.BRAND_SUBTLE};
    border-color: {colors.BRAND_PRIMARY};
    color: {colors.BRAND_ACTIVE};
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

/* ============================================================================
   Input Fields
   ============================================================================ */

#formInput, QLineEdit {{
    background-color: {colors.BG_INPUT};
    color: {colors.TEXT_PRIMARY};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
    padding: 8px 10px;
    font-size: {FONT_SIZE.BODY}px;
}}

#formInput:focus, QLineEdit:focus {{
    border-color: {colors.BRAND_PRIMARY};
    outline: 2px solid rgba(14, 165, 233, 0.2);
    outline-offset: 0px;
}}

#formInput:disabled, QLineEdit:disabled {{
    background-color: {colors.BG_APP};
    color: {colors.TEXT_TERTIARY};
}}

QComboBox {{
    background-color: {colors.BG_INPUT};
    color: {colors.TEXT_PRIMARY};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
    padding: 6px 8px;
    font-size: {FONT_SIZE.BODY}px;
}}

QComboBox:hover {{
    border-color: {colors.BRAND_PRIMARY};
}}

QComboBox::drop-down {{
    border: none;
}}

QComboBox QAbstractItemView {{
    background-color: {colors.BG_ELEVATED};
    border: 1px solid {colors.BORDER_DEFAULT};
    selection-background-color: {colors.BRAND_SUBTLE};
    selection-color: {colors.BRAND_PRIMARY};
}}

QScrollArea#toolScrollArea,
QScrollArea#manualContentScroll,
QScrollArea#settingsContentScroll {{
    border: none;
    background: transparent;
}}

QScrollArea#toolScrollArea QWidget,
QScrollArea#manualContentScroll QWidget,
QScrollArea#settingsContentScroll QWidget {{
    background: transparent;
}}

QFrame#leftMainPanel,
QFrame#rightSupportPanel,
QFrame#homeRulePanel,
QFrame#flowStrip,
QFrame#loginWorkflowPanel,
QFrame#loginBoundaryPanel,
QFrame#manualStepsPanel,
QFrame#settingsStatusPanel,
QFrame#taskCenterSummaryPanel,
QFrame#taskRow,
QFrame#scanStructureExample,
QFrame#reviewEmptyState,
QFrame#reviewStatusPanel {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.LG}px;
}}

QFrame#rightSupportPanel[surfaceRole="support"] {{
    background-color: {colors.BG_SURFACE};
}}

QFrame#preflightPanel,
QFrame#runtimePanel,
QFrame#sourceChoicePanel,
QFrame#commonOptionsPanel,
QFrame#advancedOptionsPanel,
QFrame#reviewSelectionPanel {{
    background-color: {colors.BG_HOVER};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.LG}px;
}}

QLabel#strengthPill,
QLabel#formPlaceholder,
QLabel#flowStep,
QLabel#preflightSummary {{
    padding: 9px 11px;
    background-color: {colors.BG_HOVER};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.SM}px;
    color: {colors.TEXT_SECONDARY};
}}

QToolButton#pathBrowseButton {{
    min-width: 58px;
    border: none;
    border-left: 1px solid {colors.BORDER_DEFAULT};
    background-color: {colors.BG_HOVER};
    color: {colors.BRAND_ACTIVE};
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

QToolButton#pathBrowseButton:hover {{
    background-color: {colors.BRAND_SUBTLE};
}}

QToolButton#pathBrowseButton:pressed {{
    background-color: {colors.BG_ACTIVE};
}}

QFrame#pathPicker {{
    min-height: 34px;
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.LG}px;
    background-color: {colors.BG_INPUT};
}}

QFrame#pathPicker QLineEdit#formInput {{
    border: none;
    background: transparent;
    padding: 8px 10px;
}}

QTextEdit#logBox[surfaceRole="log"] {{
    border: 1px solid {colors.BORDER_DEFAULT};
    background-color: {colors.BG_HOVER};
    color: {colors.TEXT_PRIMARY};
    font-family: {mono_family};
    font-size: 12px;
}}

QProgressBar#taskProgressBar {{
    min-height: 16px;
    max-height: 18px;
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.SM}px;
    background-color: {colors.BG_INPUT};
    color: {colors.TEXT_PRIMARY};
    text-align: center;
    font-size: {FONT_SIZE.CAPTION}px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
}}

QProgressBar#taskProgressBar::chunk {{
    border-radius: {RADIUS.SM}px;
    background-color: {colors.BRAND_PRIMARY};
}}

/* ============================================================================
   Cards and Panels
   ============================================================================ */

QFrame[objectName*="Card"], QFrame[objectName*="Panel"] {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_SUBTLE};
    border-bottom: 2px solid {shadow_light[1]};
    border-radius: {RADIUS.LG}px;
}}

#homeHero, #homeModulePanel, #homeSupportPanel {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_SUBTLE};
    border-bottom: 2px solid {shadow_light[1]};
    border-radius: {RADIUS.LG}px;
}}

#aiPreview {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_SUBTLE};
    border-radius: {RADIUS.LG}px;
}}

/* ============================================================================
   Module Cards (Homepage)
   ============================================================================ */

QPushButton[objectName="moduleCardButton"] {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_SUBTLE};
    border-bottom: 2px solid {shadow_light[1]};
    border-radius: {RADIUS.LG}px;
    padding: 10px 12px;
    text-align: center;
}}

QPushButton[objectName="moduleCardButton"]:hover {{
    border-color: {colors.BORDER_DEFAULT};
    border-bottom: 3px solid {shadow_medium[1]};
}}

/* ============================================================================
   Semantic role surfaces and feedback
   ============================================================================ */

QFrame[surfaceRole="product"] {{
    background-color: {colors.BG_APP};
    border: none;
}}

QFrame[surfaceRole="access"] {{
    background-color: {colors.BG_ELEVATED};
}}

QFrame[surfaceRole="workflow"] {{
    background-color: {colors.BRAND_SUBTLE};
    border: 1px solid {colors.BORDER_DEFAULT};
}}

QFrame[surfaceRole="boundary"] {{
    background-color: {colors.BG_HOVER};
    border: 1px solid {colors.BORDER_DEFAULT};
}}

QFrame[surfaceRole="support"] {{
    background-color: {colors.BG_SURFACE};
    border: 1px solid {colors.BORDER_DEFAULT};
}}

QTextEdit[surfaceRole="log"] {{
    background-color: {colors.BG_INPUT};
    color: {colors.TEXT_PRIMARY};
}}

QLabel[feedbackRole="explanation"] {{
    background-color: {colors.BG_HOVER};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
    color: {colors.TEXT_SECONDARY};
    padding: 9px 11px;
}}

QLabel[feedbackRole="status"] {{
    background-color: {colors.INFO_BG};
    border: 1px solid {colors.INFO_BORDER};
    border-radius: {RADIUS.MD}px;
    color: {colors.INFO};
    padding: 8px 11px;
}}

QLabel[feedbackRole="result"] {{
    background-color: {colors.SUCCESS_BG};
    border: 1px solid {colors.SUCCESS_BORDER};
    border-radius: {RADIUS.MD}px;
    color: {colors.SUCCESS};
    padding: 10px 12px;
}}

QLabel[feedbackRole="output"] {{
    background-color: {colors.BG_HOVER};
    border: 1px solid {colors.INFO_BORDER};
    border-radius: {RADIUS.MD}px;
    color: {colors.TEXT_PRIMARY};
    padding: 10px 12px;
}}

QLabel[feedbackRole="risk"],
QPushButton[buttonRole="riskConfirm"] {{
    background-color: {colors.WARNING_BG};
    border: 1px solid {colors.WARNING_BORDER};
    border-radius: {RADIUS.MD}px;
    color: {colors.WARNING};
    padding: 8px 10px;
}}

QCheckBox[feedbackRole="riskConfirm"] {{
    color: {colors.WARNING};
    spacing: 8px;
}}

QPushButton#primaryButton[buttonRole="primaryAccess"] {{
    background-color: {colors.BRAND_PRIMARY};
    color: #FFFFFF;
}}

QPushButton#secondaryButton[buttonRole="reservedAccess"] {{
    background-color: {colors.BG_ELEVATED};
    color: {colors.TEXT_SECONDARY};
}}

/* ============================================================================
   Typography
   ============================================================================ */

/* ============================================================================
   Reusable loading and empty-state components
   ============================================================================ */

QWidget#spinner {{
    color: {colors.BRAND_PRIMARY};
}}

QLabel#emptyStateTitle {{
    color: {colors.TEXT_SECONDARY};
}}

QLabel#emptyStateDescription {{
    color: {colors.TEXT_TERTIARY};
}}

QLabel#emptyStateSecondaryLink {{
    color: {colors.BRAND_PRIMARY};
}}

QLabel#loadingPanelMessage {{
    color: {colors.TEXT_SECONDARY};
}}

QWidget#skeletonLoader {{
    background-color: {colors.BG_HOVER};
    border-radius: {RADIUS.SM}px;
}}

#toolTitle {{
    font-size: {FONT_SIZE.H1}px;
    font-weight: {FONT_WEIGHT.BOLD};
    color: {colors.TEXT_PRIMARY};
    line-height: {LINE_HEIGHT.TIGHT};
}}

#homeTitle {{
    font-size: {FONT_SIZE.H1}px;
    font-weight: {FONT_WEIGHT.BOLD};
    color: {colors.TEXT_PRIMARY};
}}

#homeEyebrow, #eyebrow {{
    font-size: {FONT_SIZE.CAPTION}px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    color: {colors.TEXT_TERTIARY};
    letter-spacing: 0.5px;
}}

#smallTitle {{
    font-size: {FONT_SIZE.BODY_L}px;
    font-weight: {FONT_WEIGHT.MEDIUM};
    color: {colors.TEXT_PRIMARY};
}}

#mutedText {{
    font-size: {FONT_SIZE.BODY_S}px;
    color: {colors.TEXT_SECONDARY};
    line-height: {LINE_HEIGHT.NORMAL};
}}

#moduleTitleText {{
    font-size: {FONT_SIZE.BODY_L}px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    color: {colors.TEXT_PRIMARY};
}}

#moduleDescription {{
    font-size: {FONT_SIZE.CAPTION}px;
    color: {colors.TEXT_SECONDARY};
}}

/* ============================================================================
   Status Labels and Badges
   ============================================================================ */

QLabel[objectName="statusBadge"] {{
    font-size: {FONT_SIZE.CAPTION}px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    padding: 5px 12px;
    border-radius: {RADIUS.SM}px;
}}

/* Running status */
QLabel[objectName="statusBadge"][status="running"] {{
    background-color: {colors.SUCCESS_BG};
    color: {colors.SUCCESS};
}}

/* Completed status */
QLabel[objectName="statusBadge"][status="completed"] {{
    background-color: {colors.INFO_BG};
    color: {colors.INFO};
}}

/* Failed status */
QLabel[objectName="statusBadge"][status="failed"] {{
    background-color: {colors.ERROR_BG};
    color: {colors.ERROR};
}}

/* Warning/stopped status */
QLabel[objectName="statusBadge"][status="warning"] {{
    background-color: {colors.WARNING_BG};
    color: {colors.WARNING};
}}

/* ============================================================================
   Progress Bars
   ============================================================================ */

QProgressBar {{
    background-color: {colors.BG_INPUT};
    border: none;
    border-radius: {RADIUS.SM}px;
    text-align: center;
    /* Animations handled by QPropertyAnimation */
}}

QProgressBar::chunk {{
    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                                stop:0 {colors.BRAND_PRIMARY},
                                stop:1 {colors.BRAND_HOVER});
    border-radius: {RADIUS.SM}px;
}}

/* ============================================================================
   Scrollbars
   ============================================================================ */

QScrollBar:vertical {{
    background-color: {colors.BG_SURFACE};
    width: 12px;
    border: none;
}}

QScrollBar::handle:vertical {{
    background-color: {colors.BORDER_DEFAULT};
    border-radius: 6px;
    min-height: 30px;
}}

QScrollBar::handle:vertical:hover {{
    background-color: {colors.BORDER_EMPHASIS};
}}

QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0px;
}}

QScrollBar:horizontal {{
    background-color: {colors.BG_SURFACE};
    height: 12px;
    border: none;
}}

QScrollBar::handle:horizontal {{
    background-color: {colors.BORDER_DEFAULT};
    border-radius: 6px;
    min-width: 30px;
}}

QScrollBar::handle:horizontal:hover {{
    background-color: {colors.BORDER_EMPHASIS};
}}

QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0px;
}}

/* ============================================================================
   Login Page Specific
   ============================================================================ */

#loginStory {{
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                                stop:0 {colors.BG_APP},
                                stop:1 {colors.BG_SURFACE});
}}

#loginBrand {{
    font-size: 32px;
    font-weight: {FONT_WEIGHT.BOLD};
    color: {colors.TEXT_PRIMARY};
}}

#loginHeadline {{
    font-size: 36px;
    font-weight: {FONT_WEIGHT.BOLD};
    color: {colors.TEXT_PRIMARY};
    line-height: 1.3;
}}

#loginSubheadline {{
    font-size: 16px;
    color: {colors.TEXT_SECONDARY};
    line-height: {LINE_HEIGHT.RELAXED};
}}

#loginCard {{
    background-color: {colors.BG_ELEVATED};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.XL}px;
}}

#loginFormTitle {{
    font-size: 28px;
    font-weight: {FONT_WEIGHT.BOLD};
    color: {colors.TEXT_PRIMARY};
}}

#loginFormSubtitle {{
    font-size: {FONT_SIZE.BODY}px;
    color: {colors.TEXT_SECONDARY};
    line-height: 1.5;
}}

#loginFieldLabel {{
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.MEDIUM};
    color: {colors.TEXT_PRIMARY};
}}

#loginDescription {{
    font-size: 16px;
    font-weight: {FONT_WEIGHT.REGULAR};
    color: {colors.TEXT_SECONDARY};
    line-height: {LINE_HEIGHT.RELAXED};
}}

#loginStatReadout {{
    background: transparent;
}}

#loginStatValue {{
    font-size: 40px;
    font-weight: {FONT_WEIGHT.BOLD};
    color: {colors.BRAND_PRIMARY};
}}

#loginStatLabel {{
    font-size: {FONT_SIZE.BODY}px;
    font-weight: {FONT_WEIGHT.REGULAR};
    color: {colors.TEXT_TERTIARY};
    letter-spacing: 0.3px;
}}

#loginStatSeparator {{
    background: {colors.BORDER_SUBTLE};
    border: none;
}}

#loginStoryFooter {{
    font-size: 13px;
    color: {colors.TEXT_TERTIARY};
    line-height: 1.5;
}}

#loginCardContainer {{
    background: {colors.BG_SURFACE};
}}

#loginOptionLabel {{
    font-size: 12px;
    color: {colors.TEXT_TERTIARY};
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    letter-spacing: 0.5px;
    text-transform: uppercase;
}}

#loginForgotLink {{
    font-size: 13px;
    color: {colors.BRAND_PRIMARY};
}}

#loginForgotLink:hover {{
    color: {colors.BRAND_HOVER};
}}

/* ============================================================================
   AI Preview Panel
   ============================================================================ */

#aiTitle {{
    font-size: {FONT_SIZE.BODY_L}px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    color: {colors.TEXT_PRIMARY};
}}

#aiStatus {{
    background-color: {colors.WARNING_BG};
    color: {colors.WARNING};
    font-size: 10px;
    font-weight: {FONT_WEIGHT.SEMIBOLD};
    padding: 3px 8px;
    border-radius: {RADIUS.SM}px;
}}

#aiChip {{
    background-color: {colors.BG_HOVER};
    color: {colors.TEXT_SECONDARY};
    font-size: {FONT_SIZE.CAPTION}px;
    padding: 4px 10px;
    border-radius: {RADIUS.SM}px;
}}

#aiThread {{
    background-color: {colors.BG_ELEVATED};
    border-radius: {RADIUS.MD}px;
}}

#aiBubbleUser {{
    background-color: {colors.BRAND_SUBTLE};
    color: {colors.TEXT_PRIMARY};
    font-size: {FONT_SIZE.CAPTION}px;
    padding: 8px 10px;
    border-radius: {RADIUS.MD}px;
}}

#aiBubbleBot {{
    background-color: {colors.BG_HOVER};
    color: {colors.TEXT_SECONDARY};
    font-size: {FONT_SIZE.CAPTION}px;
    padding: 8px 10px;
    border-radius: {RADIUS.MD}px;
}}

#aiInput {{
    background-color: {colors.BG_ELEVATED};
    border: 1px solid {colors.BORDER_DEFAULT};
    border-radius: {RADIUS.MD}px;
}}

/* ============================================================================
   Error and Warning Panels
   ============================================================================ */

QFrame[objectName*="error"], QFrame[objectName*="Error"] {{
    background-color: {colors.ERROR_BG};
    border: 1px solid {colors.ERROR_BORDER};
    border-left: 4px solid {colors.ERROR};
    border-radius: {RADIUS.MD}px;
}}

QFrame[objectName*="warning"], QFrame[objectName*="Warning"] {{
    background-color: {colors.WARNING_BG};
    border: 1px solid {colors.WARNING_BORDER};
    border-left: 4px solid {colors.WARNING};
    border-radius: {RADIUS.MD}px;
}}

QFrame[objectName*="success"], QFrame[objectName*="Success"] {{
    background-color: {colors.SUCCESS_BG};
    border: 1px solid {colors.SUCCESS_BORDER};
    border-left: 4px solid {colors.SUCCESS};
    border-radius: {RADIUS.MD}px;
}}

/* ============================================================================
   End of Stylesheet
   ============================================================================ */
        """

        return stylesheet.strip()


# Module-level singleton accessor
_theme_manager_instance: ThemeManager | None = None


def get_theme_manager() -> ThemeManager:
    """
    Get the singleton ThemeManager instance.

    Returns:
        ThemeManager singleton instance
    """
    global _theme_manager_instance
    if _theme_manager_instance is None:
        _theme_manager_instance = ThemeManager()
    return _theme_manager_instance


__all__ = [
    "ThemeManager",
    "get_theme_manager",
]
